@eidepozo

## Medición de diversidad

Incluye la exportación del dataset con su valor de diversidad $sum\_cos$, definido como: *la suma de cada par único de snippets bajo similitud del coseno (sim)* 

\begin{equation}
\label{eqn:sum_cos}
sum\_cos(q) = \sum_{\substack{i \in I \\ i < j}} \sum_{j \in I} sim(s_{i}, s_{j}), \quad s_i, s_j \in S
\end{equation}

con $N$ snippets e $I = \{1,\ldots, N\}$


In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
    
from src.data_extraction import data_extraction
from src.filtering import filtering

In [2]:
data = data_extraction(4) 

In [3]:
from bs4 import BeautifulSoup

In [4]:
data['snippet'] = data['snippet'].map(lambda text: BeautifulSoup(text, 'html.parser').get_text())

In [5]:
aux = data.groupby('id_number').head(3).groupby('FK_student_nick').head(3)
#aux # 3 primeros resultados para cada usuario de su primera query emitida

In [6]:
df = aux.drop_duplicates(['FK_student_nick','query'])[['FK_student_nick', 'query']] # primera query unica
df = df.reset_index(drop=True)

In [7]:
df['snippet1'] = aux['snippet'].iloc[::3].reset_index(drop=True) # 3 documentos por usuario
df['snippet2'] = aux['snippet'].iloc[1::3].reset_index(drop=True)
df['snippet3'] = aux['snippet'].iloc[2::3].reset_index(drop=True)

In [8]:
df

FK_student_nick                                              query  \
0       aarriagada                        como construir un automovil   
1          cduarte                                            soapbox   
2         abastian                               Crear un auto básico   
3       ocontreras                         Como construir un automovi   
4         gcurguan                 Como construir un auto de carreras   
5           mcarep                  construir automovil derby soapbox   
6        eespinoza           como construir un automovil de carrerqas   
7         gandrade   que debe tener mi auto para competir en nascar?    
8       jfernandez                                                asd   
9          bcortes                        componentes de un automovil   
10    nguentalican                        como construir un automovil   
11          dhofer                 plan basico para construir un auto   
12       mescobarp                             partes de un automovil   
13      chenriquez                            construir un automóvil    
14         lguzman                        como construir un automovil   
15          jgomez                            roblox como crear autos   
16         mcatril                     como crear un auto para nazcar   
17       fcastillo                    diseños basicos de un automovil   
18      marriagada                        como construir un automovil   
19        nhuaquil               pasos basicos para construir un auto   
20         mgatica             Como construir un automovil de carrera   
21        rfuentes                  pasos para construir un automovil   
22        jbarriap               como hace un auto en chile en python   
23       mgallardo             carateristicas necesarias para un auto   
24        ahidalgo  diseños basicos para la construccion de un aut...   
25     ehernandesp  como hacer un auto para carreras de derby de s...   
26       jgonzalez                                   soapbox carreras   
27         scortez                        como construir un automovil   
28       falvarado                       arquitectura de un automovil   
29          aduque                                      autos soapbox   

                                             snippet1  \
0   Cómo construir un auto deportivo con poco dine...   
1   Soapbox is a Chrome extension that enables any...   
2   This feature is not available right now. Pleas...   
3   Construir un motor de automóvil desde cero, ll...   
4   QUIERES FORMAR PARTE DE LA MEJOR NETWORK DE YO...   
5   Fácil Soap Box Derby coche construir Estas ins...   
6   Construye un automóvil de carreras casero y se...   
7   Están preparados para competir más de 500 mill...   
8   Anchorage School District website accessibilit...   
9   El primer viaje largo en un automóvil lo reali...   
10  Cómo construir un auto deportivo con poco dine...   
11  Cómo construir un go kart. En este artículo: P...   
12  Chasis Chasis de un automóvil. Constituye la e...   
13  La fabricación de automóviles se refiere a la ...   
14  Cómo construir un auto deportivo con poco dine...   
15  Como CREAR TU PROPIO COCHE en ROBLOX muy FACIL...   
16  La tecnología de innovación de los últimos año...   
17  El término automóvil (del griego auto, "por sí...   
18  Cómo construir un auto deportivo con poco dine...   
19  Guía paso a paso para construir tu propio auto...   
20  Construye un automóvil de carreras casero y se...   
21  Los 8 pasos esenciales para crear un auto El p...   
22  Stack Overflow en español es un sitio de pregu...   
23  La siguiente figura resume rápidamente la func...   
24  Durante años el chasis tal y como se ha explic...   
25  Inspírate para Red Bull Soapbox Race con 10 au...   
26  Una curiosa y bizarra carrera se desarrolla en...   
27  Cómo construir un auto deportivo con poco dine...   
28  La relación entre automóviles y arquitectura n...   
29  Encuentra el Seguro Oblig

In [9]:
#https://goodboychan.github.io/chans_jupyter/python/datacamp/natural_language_processing/2020/07/17/04-TF-IDF-and-similarity-scores.html#Cosine-similarity
#https://gist.github.com/4OH4/bea12f336b154e25ac33acbc76cd5f0a

from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

In [10]:
es_sw = stopwords.words('spanish')

In [11]:
tf = TfidfVectorizer(stop_words=es_sw) 

In [12]:
from recomendacion_de_terminos.src.metrics import sim_matrix, group_matrix
import numpy as np

Ej. del proceso para query 20

In [13]:
q = df['query'][20]
s1 = df['snippet1'][20]
s2 = df['snippet2'][20]
s3 = df['snippet3'][20]

In [14]:
q

'Como construir un automovil de carrera'

In [15]:
tfidf_matrix = tf.fit_transform([q,s1,s2,s3]) # matriz de caracteristicas

In [16]:
feature_names = tf.get_feature_names()
for x in feature_names:
    print(x, end=' ')

aerodinámica auto automotriz automovil automóvil carrera carreras casero colección computarizados construcción construir construye controles cuenca duda electrónicos enseñaremos estilo estudiantes forma fórmula grupo hacemos historia ingeniería juego juegos madera mantiene mayor miembro mismos objeto parte pasatiempo pertenecientes politécnica proyecto puede realizan salesiana sede selecto ser si universidad valor vehículo vida 

In [17]:
print(tfidf_matrix[0])

  (0, 5)	0.4480997313625986
  (0, 3)	0.7020348194149619
  (0, 11)	0.5534923152870045


In [18]:
from sklearn.metrics.pairwise import linear_kernel

In [19]:
S = [] # estimacion de similitud del coseno
for i in range(4): # largo del corpus
    S.append(linear_kernel(tfidf_matrix[i], tfidf_matrix).flatten())

In [20]:
S = np.asarray((S[0],S[1],S[2],S[3]))

In [21]:
S

array([[1.        , 0.        , 0.21377703, 0.14469256],
       [0.        , 1.        , 0.        , 0.        ],
       [0.21377703, 0.        , 1.        , 0.08738573],
       [0.14469256, 0.        , 0.08738573, 1.        ]])

In [22]:
tf = TfidfVectorizer(stop_words=es_sw)  # reset para aplicar la funcion a los participantes

In [23]:
S = group_matrix(df, tf)

In [24]:
S # matriz de similitud

array([[[ 0.00000000e+00,  8.96145770e-01,  9.37722385e-01,
          1.00000000e+00],
        [ 8.96145770e-01,  4.44089210e-16,  9.77656827e-01,
          9.32096698e-01],
        [ 9.37722385e-01,  9.77656827e-01,  0.00000000e+00,
          1.00000000e+00],
        [ 1.00000000e+00,  9.32096698e-01,  1.00000000e+00,
          4.44089210e-16]],

       [[ 0.00000000e+00,  8.53618062e-01,  9.03598882e-01,
          9.26229180e-01],
        [ 8.53618062e-01,  5.55111512e-16,  8.79243984e-01,
          9.40734053e-01],
        [ 9.03598882e-01,  8.79243984e-01,  1.11022302e-16,
          8.79805527e-01],
        [ 9.26229180e-01,  9.40734053e-01,  8.79805527e-01,
          4.44089210e-16]],

       [[ 0.00000000e+00,  1.00000000e+00,  9.33335540e-01,
          9.14881962e-01],
        [ 1.00000000e+00,  4.44089210e-16,  1.00000000e+00,
          1.00000000e+00],
        [ 9.33335540e-01,  1.00000000e+00,  7.77156117e-16,
          9.88811239e-01],
        [ 9.14881962e-01,  1.00000000e+

In [25]:
S[0] # 29 submatrices de similitud por usuario, query y 3 snippets respectivas

array([[0.00000000e+00, 8.96145770e-01, 9.37722385e-01, 1.00000000e+00],
       [8.96145770e-01, 4.44089210e-16, 9.77656827e-01, 9.32096698e-01],
       [9.37722385e-01, 9.77656827e-01, 0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 9.32096698e-01, 1.00000000e+00, 4.44089210e-16]])

In [26]:
df['sum_cos'] = "" # arreglo

In [27]:
# estimación del "puntaje del coseno" = suma de similaridad entre snippets por usuario
# a medida que disminuye mayor es la diversidad
for i in range(S.shape[0]):
    df['sum_cos'][i] = S[i][1,2] + S[i][1,3] + S[i][2,3]

In [28]:
df

FK_student_nick                                              query  \
0       aarriagada                        como construir un automovil   
1          cduarte                                            soapbox   
2         abastian                               Crear un auto básico   
3       ocontreras                         Como construir un automovi   
4         gcurguan                 Como construir un auto de carreras   
5           mcarep                  construir automovil derby soapbox   
6        eespinoza           como construir un automovil de carrerqas   
7         gandrade   que debe tener mi auto para competir en nascar?    
8       jfernandez                                                asd   
9          bcortes                        componentes de un automovil   
10    nguentalican                        como construir un automovil   
11          dhofer                 plan basico para construir un auto   
12       mescobarp                             partes de un automovil   
13      chenriquez                            construir un automóvil    
14         lguzman                        como construir un automovil   
15          jgomez                            roblox como crear autos   
16         mcatril                     como crear un auto para nazcar   
17       fcastillo                    diseños basicos de un automovil   
18      marriagada                        como construir un automovil   
19        nhuaquil               pasos basicos para construir un auto   
20         mgatica             Como construir un automovil de carrera   
21        rfuentes                  pasos para construir un automovil   
22        jbarriap               como hace un auto en chile en python   
23       mgallardo             carateristicas necesarias para un auto   
24        ahidalgo  diseños basicos para la construccion de un aut...   
25     ehernandesp  como hacer un auto para carreras de derby de s...   
26       jgonzalez                                   soapbox carreras   
27         scortez                        como construir un automovil   
28       falvarado                       arquitectura de un automovil   
29          aduque                                      autos soapbox   

                                             snippet1  \
0   Cómo construir un auto deportivo con poco dine...   
1   Soapbox is a Chrome extension that enables any...   
2   This feature is not available right now. Pleas...   
3   Construir un motor de automóvil desde cero, ll...   
4   QUIERES FORMAR PARTE DE LA MEJOR NETWORK DE YO...   
5   Fácil Soap Box Derby coche construir Estas ins...   
6   Construye un automóvil de carreras casero y se...   
7   Están preparados para competir más de 500 mill...   
8   Anchorage School District website accessibilit...   
9   El primer viaje largo en un automóvil lo reali...   
10  Cómo construir un auto deportivo con poco dine...   
11  Cómo construir un go kart. En este artículo: P...   
12  Chasis Chasis de un automóvil. Constituye la e...   
13  La fabricación de automóviles se refiere a la ...   
14  Cómo construir un auto deportivo con poco dine...   
15  Como CREAR TU PROPIO COCHE en ROBLOX muy FACIL...   
16  La tecnología de innovación de los últimos año...   
17  El término automóvil (del griego auto, "por sí...   
18  Cómo construir un auto deportivo con poco dine...   
19  Guía paso a paso para construir tu propio auto...   
20  Construye un automóvil de carreras casero y se...   
21  Los 8 pasos esenciales para crear un auto El p...   
22  Stack Overflow en español es un sitio de pregu...   
23  La siguiente figura resume rápidamente la func...   
24  Durante años el chasis tal y como se ha explic...   
25  Inspírate para Red Bull Soapbox Race con 10 au...   
26  Una curiosa y bizarra carrera se desarrolla en...   
27  Cómo construir un auto deportivo con poco dine...   
28  La relación entre automóviles y arquitectura n...   
29  Encuentra el Seguro Oblig

In [29]:
#df.to_csv('participants_ext_2.csv', index=False)